alert('WELCOME TO BLOKCHAIN COURSE')
alert("Coding with Fun")

console.log("hello World ")   //Shows output on Console.
console.log(2+2)    //We can put anything inside the log.(Array,String,Bool,Object
console.log("Muhammad Haseeb Jawad");
console.log(true);
console.log([1,2,3]);
console.log({name:'Haseeb',Language:"Javascript",Tutorial: 1});
console.table({name:"M.Haseeb Jawad",Language:"Javascript",Tutorial:1});

//!console.clear();// It should clear the console

console.time();
for(i=0;i<100;i++)
{
    
}
console.timeEnd();   //todo **** We can find the amount of time spend by code on execution

console.warn("This is Warning"); //! For Warning we use console.warn

//document.write("Coding With Fun"); //? Dispaly message on Browser
document.write(2+2);

var nationalit = "Pakistani ";
console.log(nationalit);

let age = 25;
console.log(age);

var nationalit = "indian ";
console.log(nationalit);

let name = "haseeb";
console.log(name);

const num = 10;
console.log(num);










